# Model Controller Tutorial: EnviBert model

> This notebook contains some example of how to use the EnviBert-based models in this NLP library

- skip_showdoc: true
- skip_exec: true

In [ ]:
%reload_ext autoreload
%autoreload 2

In [ ]:
#| hide
from nbdev.showdoc import *

## Load data

We will reuse the sample data in [this tutorial](https://anhquan0412.github.io/that-nlp-library/text_main.html) to experiment with the models

In [ ]:
from that_nlp_library.text_transformation import *
from that_nlp_library.text_augmentation import *
from that_nlp_library.text_main import *

In [ ]:
from underthesea import text_normalize
from functools import partial
from pathlib import Path
from importlib.machinery import SourceFileLoader
import os
from transformers import DataCollatorWithPadding

Define some necessary text augmentations and text transformations

> For Text Transformation

In [ ]:
txt_tfms=[text_normalize]

> For Text Augmentation

In [ ]:
over_nonown_tfm = partial(sampling_with_condition,query='Source=="non owned"',frac=0.5,seed=42,apply_to_all=False)
over_nonown_tfm.__name__ = 'Oversampling Non Owned'

over_own_tfm = partial(sampling_with_condition,query='Source=="owned"',frac=2,seed=42,apply_to_all=False)
over_own_tfm.__name__ = 'Oversampling Owned'

over_hc_tfm = partial(sampling_with_condition,query='Source=="hc search"',frac=2.5,seed=42,apply_to_all=False)
over_hc_tfm.__name__ = 'Oversampling HC search'

remove_accent_tfm = partial(remove_vnmese_accent,frac=1,seed=42,apply_to_all=True)
remove_accent_tfm.__name__ = 'Add No-Accent Text'

aug_tfms = [over_nonown_tfm,over_own_tfm,over_hc_tfm,remove_accent_tfm]

Create a TextDataMain object

In [ ]:
DATA_PATH = Path('sample_data')

In [ ]:
tdm = TextDataMain.from_csv(DATA_PATH/'sample.csv',
                            return_df=False,
                            main_content='Content',
                            metadatas='Source',
                            label_names='L1',
                            val_ratio=0.2,
                            split_cols='L1',
                            content_tfms = txt_tfms,
                            aug_tfms = aug_tfms,
                            process_metadatas=True,
                            seed=42,
                            shuffle_trn=True)

----- Input Validation Precheck -----

Define our tokenizer for EnviBert

In [ ]:
cache_dir=Path('./envibert_tokenizer')
tokenizer = SourceFileLoader("envibert.tokenizer", 
                             str(cache_dir/'envibert_tokenizer.py')).load_module().RobertaTokenizer(cache_dir)

In [ ]:
# # EnviBert a data collator to work. We will save this as an attribute in TDM
# data_collator = DataCollatorWithPadding(tokenizer,padding=True,max_length=512)
# tdm.set_data_collator(data_collator)

Create our DatasetDict from TextDataMain (as our `ModelController` class can also work with DatasetDict)

In [ ]:
main_ddict= tdm.to_datasetdict(tokenizer,
                                max_length=512,
                              )

-------------------- Start Main Text Processing --------------------
----- Metadata Simple Processing & Concatenating to Main Content -----
----- Label Encoding -----
-------------------- Text Transformation --------------------
----- text_normalize -----

100%|██████████████████████████████████████| 70/70 [00:00<00:00, 5737.76it/s]

-------------------- Train Test Split --------------------
Previous Validation Percentage: 20.0%
- Before leak check
Size: 14
- After leak check
Size: 14
- Number of rows leaked: 0, or 0.00% of the original validation (or test) data
Current Validation Percentage: 20.0%
-------------------- Text Augmentation --------------------
Train data size before augmentation: 56
----- Oversampling Non Owned -----
Train data size after THIS augmentation: 61
----- Oversampling Owned -----
Train data size after THIS augmentation: 63
----- Oversampling HC search -----
Train data size after THIS augmentation: 73
----- Add No-Accent Text -----

100%|█████████████████████████████████████| 73/73 [00:00<00:00, 24597.06it/s]

Train data size after THIS augmentation: 146
Train data size after ALL augmentation: 146
-------------------- Map Tokenize Function --------------------

Map:   0%|          | 0/146 [00:00<?, ? examples/s]

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

In [ ]:
main_ddict

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'Source', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 146
    })
    validation: Dataset({
        features: ['text', 'label', 'Source', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 14
    })
})

Let's see some examples of outputs the TDM produces:

In [ ]:
two_steps_tokenization_explain('Tôi đặt hàng mà chẳng thấy giao 1 năm rồi.Làm với chả ăn,chán 🤬 🤬 🤬 🤬 🤬 🤬',
                               tokenizer,content_tfms=[text_normalize])

----- Text Transformation Explained -----
--- Raw sentence ---
Tôi đặt hàng mà chẳng thấy giao 1 năm rồi.Làm với chả ăn,chán 🤬 🤬 🤬 🤬 🤬 🤬
--- text_normalize ---
Tôi đặt hàng mà chẳng thấy giao 1 năm rồi . Làm với chả ăn , chán 🤬 🤬 🤬 🤬 🤬 🤬

----- Tokenizer Explained -----
--- Input ---
Tôi đặt hàng mà chẳng thấy giao 1 năm rồi . Làm với chả ăn , chán 🤬 🤬 🤬 🤬 🤬 🤬

--- Tokenized results ---
{'input_ids': [0, 842, 642, 114, 145, 1371, 289, 363, 139, 93, 539, 5, 3798, 39, 7225, 380, 4, 5925, 3529, 3, 3529, 3, 3529, 3, 3529, 3, 3529, 3, 3529, 3, 2], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

--- Results from tokenizer.convert_ids_to_tokens ---
['<s>', '▁Tôi', '▁đặt', '▁hàng', '▁mà', '▁chẳng', '▁thấy', '▁giao', '▁1', '▁năm', '▁rồi', '▁.', '▁Làm', '▁với', '▁chả', '▁ăn', '▁,', '▁chán', '▁', '<unk>', '▁', '<unk>', '▁', '<unk>', '▁', '<unk>', '▁', '<unk>', '▁', '<unk>', '</s>']

--- Results from tokenizer.decode ---
<s> ▁Tôi ▁đặt ▁hàng ▁mà ▁chẳng ▁thấy ▁giao ▁1 ▁năm ▁rồi ▁. ▁Làm ▁với ▁chả ▁ăn ▁, ▁chán ▁ <unk> ▁ <unk> ▁ <unk> ▁ <unk> ▁ <unk> ▁ <unk> </s>

In [ ]:
tdm.tokenizer_explain_single(tokenizer) # Pick a random text in train set to explain

----- Tokenizer Explained -----
--- Input ---
ios - Toi rat that vong dich vu cua shoppee toi mua san pham cua dich vu khong ai giao den hay goi ma bao voi he thong la giao hang khong thanh cong con them dia chi ko ro rang nua chu . Nieu dich vu shoppee tlam ko noi thi dung lam nua chuyen nghe di .

--- Tokenized results ---
{'input_ids': [0, 87, 1344, 13, 1449, 592, 14580, 18, 2886, 29254, 10209, 8131, 3659, 1516, 3786, 38678, 442, 6046, 49069, 8131, 29254, 10209, 24836, 824, 363, 10391, 292, 52093, 1986, 507, 8340, 42, 19850, 2267, 363, 4173, 24836, 656, 5536, 176, 187, 36846, 590, 4111, 3636, 9069, 36814, 4169, 5, 756, 13295, 29254, 10209, 3659, 1516, 3786, 67, 11347, 4111, 16494, 392, 936, 7339, 36814, 34196, 1101, 943, 5, 2], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

--- Results from tokenizer.convert_ids_to_tokens ---
['<s>', '▁i', 'os', '▁-', '▁To', 'i', '▁rat', '▁that', '▁vong', '▁dich', '▁vu', '▁cua', '▁shop', 'p', 'ee', '▁toi', '▁mua', '▁san', '▁pham', '▁cua', '▁dich', '▁vu', '▁khong', '▁ai', '▁giao', '▁den', '▁hay', '▁goi', '▁ma', '▁bao', '▁voi', '▁he', '▁thong', '▁la', '▁giao', '▁hang', '▁khong', '▁thanh', '▁cong', '▁con', '▁them', '▁dia', '▁chi', '▁ko', '▁ro', '▁rang', '▁nua', '▁chu', '▁.', '▁N', 'ieu', '▁dich', '▁vu', '▁shop', 'p', 'ee', '▁t', 'lam', '▁ko', '▁noi', '▁thi', '▁dung', '▁lam', '▁nua', '▁chuyen', '▁nghe', '▁di', '▁.', '</s>']

--- Results from tokenizer.decode ---
<s> ▁i os ▁- ▁To i ▁rat ▁that ▁vong ▁dich ▁vu ▁cua ▁shop p ee ▁toi ▁mua ▁san ▁pham ▁cua ▁dich ▁vu ▁khong ▁ai ▁giao ▁den ▁hay ▁goi ▁ma ▁bao ▁voi ▁he ▁thong ▁la ▁giao ▁hang ▁khong ▁thanh ▁cong ▁con ▁them ▁dia ▁chi ▁ko ▁ro ▁rang ▁nua ▁chu ▁. ▁N ieu ▁dich ▁vu ▁shop p ee ▁t lam ▁ko ▁noi ▁thi ▁dung ▁lam ▁nua ▁chuyen ▁nghe ▁di ▁. </s>

# Model Experiment: EnviBert Single-Head Classification (with Hidden Layer Concatenation)

In [ ]:
from that_nlp_library.models.classifiers import *
from that_nlp_library.models.conditional_prob_classifiers import *
from that_nlp_library.models.deep_hierarchical_classifiers import *

In [ ]:
from that_nlp_library.model_main import *

comet_ml is installed but `COMET_API_KEY` is not set.

In [ ]:
from sklearn.metrics import f1_score, accuracy_score

In [ ]:
main_ddict

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'Source', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 146
    })
    validation: Dataset({
        features: ['text', 'label', 'Source', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 14
    })
})

## Train EnviBert (with hidden layer concatenation), using TDM

In [ ]:
tdm.label_lists

[['Buyer complained seller',
  'Commercial',
  'Delivery',
  'Feature',
  'Order/Item',
  'Others',
  'Payment',
  'Return/Refund',
  'Services',
  'Shopee account']]

Let's create our model controller

In [ ]:
num_classes = len(tdm.label_lists[0]) # 10

_model_kwargs={
    'concathead_class': RobertaConcatHeadSimple,
    'classifier_dropout':0.1,
    'last_hidden_size':768,  
    'is_multilabel':tdm.is_multilabel, # False
    'is_multihead':tdm.is_multihead, # False
    'head_class_sizes':num_classes
}

model = model_init_classification(model_class = RobertaHiddenStateConcatForSequenceClassification,
                                  cpoint_path = 'nguyenvulebinh/envibert', 
                                  output_hidden_states=True, # since we are using 'hidden layer contatenation'
                                  seed=42,
                                  model_kwargs = _model_kwargs)

metric_funcs = [partial(f1_score,average='macro'),accuracy_score] # we will use both f1_macro and accuracy score as metrics
controller = ModelController(model,tdm,metric_funcs)

Some weights of the model checkpoint at nguyenvulebinh/envibert were not used when initializing RobertaHiddenStateConcatForSequenceClassification: ['lm_head.layer_norm.bias', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.weight', 'lm_head.bias']
- This IS expected if you are initializing RobertaHiddenStateConcatForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaHiddenStateConcatForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaHiddenStateConcatForSequenceClassification were not initialized from the model checkpoint at nguyenvulebinh/envibert and are newly initialized: ['classification_head.out_proj.bias', 'classification_head.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

And we can start training our model

In [ ]:
lr = 8e-5
bs=4
wd=0.01
epochs= 1

controller.fit(epochs,lr,
               batch_size=bs,
               weight_decay=wd,
               save_checkpoint=False,
               compute_metrics=compute_metrics_classification,
              )

/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py:32: UserWarning:
    There is an imbalance between your GPUs. You may want to exclude GPU 1 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '

### Logging your training

You can log your training using HuggingFace:

- Supported platforms are "azure_ml", "comet_ml", "mlflow", "neptune", "tensorboard","clearml" and "wandb"

- References:

    - https://huggingface.co/docs/transformers/v4.28.0/en/main_classes/trainer#transformers.TrainingArguments
    
    - https://docs.wandb.ai/guides/integrations/huggingface#:~:text=Logging%20your%20Hugging%20Face%20model,every%20save_steps%20in%20the%20TrainingArguments%20.

```python
controller.fit(epochs,lr,
               batch_size=bs,
               weight_decay=wd,
               save_checkpoint=False,
               compute_metrics=compute_metrics_classification,
               hf_report_to='wandb'
              )
```

You can save your model weights at the end of your training

```python
controller.trainer.model.save_pretrained('./sample_weights/model_progress')
```

Or you can save your weights at every epochs during your training

```python
controller.fit(epochs,lr,
               batch_size=bs,
               weight_decay=wd,
               save_checkpoint=True,
               o_dir='sample_weights',
               compute_metrics=compute_metrics_classification,
              )
```

## Train EnviBert (with hidden layer concatenation), with tokenized DatasetDict

Assume you already have your tokenized datasetdict. You must include your tokenizer.

In [ ]:
tokenizer

RobertaTokenizer(name_or_path='', vocab_size=59993, model_max_length=1000000000000000019884624838656, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': '<mask>'}, clean_up_tokenization_spaces=True)

Note that your DatasetDict must contain tokens besides raw text (which typically includes 'input_ids', 'token_type_ids', 'attention_mask')

In [ ]:
main_ddict

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'Source', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 146
    })
    validation: Dataset({
        features: ['text', 'label', 'Source', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 14
    })
})

In [ ]:
num_classes = 10

_model_kwargs={
    'concathead_class': RobertaConcatHeadSimple,
    'classifier_dropout':0.1,
    'last_hidden_size':768,  
    'is_multilabel':False,
    'is_multihead': False,
    'head_class_sizes':num_classes
}

model = model_init_classification(model_class = RobertaHiddenStateConcatForSequenceClassification,
                                  cpoint_path = 'nguyenvulebinh/envibert', 
                                  output_hidden_states=True, # since we are using 'hidden layer contatenation'
                                  seed=42,
                                  model_kwargs = _model_kwargs)

metric_funcs = [partial(f1_score,average='macro'),accuracy_score] # we will use both f1_macro and accuracy score as metrics
controller = ModelController(model,
                             metric_funcs=metric_funcs)

Some weights of the model checkpoint at nguyenvulebinh/envibert were not used when initializing RobertaHiddenStateConcatForSequenceClassification: ['lm_head.layer_norm.bias', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.weight', 'lm_head.bias']
- This IS expected if you are initializing RobertaHiddenStateConcatForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaHiddenStateConcatForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaHiddenStateConcatForSequenceClassification were not initialized from the model checkpoint at nguyenvulebinh/envibert and are newly initialized: ['classification_head.out_proj.bias', 'classification_head.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
lr = 8e-5
bs=4
wd=0.01
epochs= 1

controller.fit(epochs,lr,
               ddict=main_ddict, # Put in your tokenized datasetdict here
               batch_size=bs,
               weight_decay=wd,
               save_checkpoint=False,
               compute_metrics=compute_metrics_classification,
               tokenizer=tokenizer,
               label_names='L1'
              )

/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py:32: UserWarning:
    There is an imbalance between your GPUs. You may want to exclude GPU 1 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '

## Predict using trained model, using TDM

### Load trained model

```python
trained_model = model_init_classification(model_class = RobertaHiddenStateConcatForSequenceClassification,
                                  cpoint_path = Path('./sample_weights/model_progress'), 
                                  output_hidden_states=True,
                                  seed=42,
                                  model_kwargs = _model_kwargs)
```

```python
metric_funcs = [partial(f1_score,average='macro'),accuracy_score] # we will use both f1_macro and accuracy score as metrics
controller = ModelController(model,tdm,metric_funcs)
```

### Predict Train/Validation set

Make prediction on all validation set

```python
df_val = controller.predict_ddict(ds_type='validation')
```

```python
df_val.head()
```

| text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |   label | Source      | pred_L1                 |   pred_prob_L1 |
|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------:|:------------|:------------------------|---------------:|
| owned - [ Cảnh báo ] bán fa.ke giả mạo Shop Mall . Mọi người ơi , đêm qua mình vừa mua shop này chai dầu dưỡng tóc . Do tối buồn ngủ nên mình mắt nhắm mắt mở đặt shop này . Sáng ra khi check lại đơn thì mình mới phát hình shop này đã photoshop , chèn tag Mall vào hình ảnh sản phẩm mặc dù shop không có tag gì hết . Mình vội vàng hủy đơn và rp đến Shopee . Mọi người mua hàng nhớ cẩn thận check hình ảnh và uy tín shop rõ ràng nha : ( ( ( ( # NghienShopee # Canhbao # Fake                                     |       0 | owned       | Buyer complained seller |       0.78914  |
| google play - Chính sách trả hàng hoàn tiền không hợp lý . Thiếu công bằng , không bảo vệ quyền lợi của người bán . Mình đã tắt bán hàng trên Shopee và chuyển sang lazada .                                                                                                                                                                                                                                                                                                                                                 |       7 | google play | Return/Refund           |       0.976054 |
| google play - Hi vọng shopee kiểm duyệt phản hồi đánh giá của khách hàng chặt chẽ và chính xác hơn . Bởi vì có nhiều người chụp đăng hình ảnh ko liên quan và những ký tự vô nghĩa gggghkkkdjdbdjdbsosb nhằm mục đích nhận xu , không có giá trị tham khảo cho những người mua sau mà shopee vẫn cho đăng . Còn mình đánh giá càng chi tiết , muốn đem lại giá trị tham khảo cho người sau thì bị hệ thống kêu trùng lặp ký tự , phải chỉnh sửa cả chục cả trăm lần rất mất thời gian , vẫn không hợp lệ và ko có cho đăng . |       3 | google play | Feature                 |       0.582839 |
| google play - Shoppe bị lỗi r ....                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |       5 | google play | Feature                 |       0.760949 |
| google play - Hàng không đặt được gì hết một sao                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |       9 | google play | Others                  |       0.735695 |

To convert the label index to string, we can use the ```label_lists``` attribute of tdm

```python
df_val['label']= df_val['label'].apply(lambda x: tdm.label_lists[0][x]).values

df_val.head()
```

| text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | label                   | Source      | pred_L1                 |   pred_prob_L1 |
|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:------------------------|:------------|:------------------------|---------------:|
| owned - [ Cảnh báo ] bán fa.ke giả mạo Shop Mall . Mọi người ơi , đêm qua mình vừa mua shop này chai dầu dưỡng tóc . Do tối buồn ngủ nên mình mắt nhắm mắt mở đặt shop này . Sáng ra khi check lại đơn thì mình mới phát hình shop này đã photoshop , chèn tag Mall vào hình ảnh sản phẩm mặc dù shop không có tag gì hết . Mình vội vàng hủy đơn và rp đến Shopee . Mọi người mua hàng nhớ cẩn thận check hình ảnh và uy tín shop rõ ràng nha : ( ( ( ( # NghienShopee # Canhbao # Fake                                     | Buyer complained seller | owned       | Buyer complained seller |       0.78914  |
| google play - Chính sách trả hàng hoàn tiền không hợp lý . Thiếu công bằng , không bảo vệ quyền lợi của người bán . Mình đã tắt bán hàng trên Shopee và chuyển sang lazada .                                                                                                                                                                                                                                                                                                                                                 | Return/Refund           | google play | Return/Refund           |       0.976054 |
| google play - Hi vọng shopee kiểm duyệt phản hồi đánh giá của khách hàng chặt chẽ và chính xác hơn . Bởi vì có nhiều người chụp đăng hình ảnh ko liên quan và những ký tự vô nghĩa gggghkkkdjdbdjdbsosb nhằm mục đích nhận xu , không có giá trị tham khảo cho những người mua sau mà shopee vẫn cho đăng . Còn mình đánh giá càng chi tiết , muốn đem lại giá trị tham khảo cho người sau thì bị hệ thống kêu trùng lặp ký tự , phải chỉnh sửa cả chục cả trăm lần rất mất thời gian , vẫn không hợp lệ và ko có cho đăng . | Feature                 | google play | Feature                 |       0.582839 |
| google play - Shoppe bị lỗi r ....                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | Others                  | google play | Feature                 |       0.760949 |
| google play - Hàng không đặt được gì hết một sao                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | Shopee account          | google play | Others                  |       0.735695 |

You can try to get your metric to see if it matches your last traing epoch's above

```f1_score(df_val.label,df_val.pred_L1,average='macro')```

You can also make predictions on all training set, by changing argument ```ds_type``` to "train"

### Predict Test set

We will go through details on how to make a prediction on a completely new and raw dataset using our trained model. For now, let's reuse the sample csv and pretend it's our test set

In [ ]:
df_test = TextDataMain.from_csv(Path('sample_data')/'sample.csv',return_df=True)

----- Input Validation Precheck -----

We will remove all the labels and unnecessary columns

In [ ]:
df_test = df_test.drop(['L1','L2'],axis=1)

In [ ]:
df_test.head()

         Group       Source                                            Content
0  Google Play  Google Play  Mình khuyên các bạn nên mua bên Lazada hoặc Ti...
1  Google Play  Google Play                          Con cc quoảng cáu ít thôi
2          iOS          iOS  Mình có một vài món hàng shipper ấn giao r mà ...
3  Google Play  Google Play  Mình đã sử dụng shoppe cũng 1 thời gian dài rồ...
4  Google Play  Google Play  Chăm sóc khách hàng quá tệ. Nhân viên hỗ trợ c...

We will create a DatasetDict for this test dataframe

In [ ]:
test_ddict = tdm.get_test_datasetdict_from_df(df_test)

-------------------- Getting Test Set --------------------
----- Input Validation Precheck -----
-------------------- Start Test Set Transformation --------------------
----- Metadata Simple Processing & Concatenating to Main Content -----
-------------------- Text Transformation --------------------
----- text_normalize -----

100%|██████████████████████████████████████| 70/70 [00:00<00:00, 6234.76it/s]

-------------------- Test Leak Checking --------------------
- Before leak check
Size: 70
- After leak check
Size: 0
- Number of rows leaked: 70, or 100.00% of the original validation (or test) data
-------------------- Construct DatasetDict --------------------

Map:   0%|          | 0/70 [00:00<?, ? examples/s]

Remember the ***Leak Check*** we did in TextDataMain? Our ```df_test``` only has 70 rows, and it also shows that 70 rows of our data is leaked (100%), which is correct because this test dataset is actually a small sample of the training data.

In [ ]:
test_ddict

DatasetDict({
    test: Dataset({
        features: ['text', 'Source', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 70
    })
})

Our test data has been processed + transformed (but not augmented) the same way as the validation set. Now we can start making the prediction

```python
controller = ModelController(model,tdm)
df_result = controller.predict_ddict(ddict=test_ddict,ds_type='test')
```

```python
df_result.head()
```

| text                                                                                                                                                                                                                                                       | Source      | pred_L1   |   pred_prob_L1 |
|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:------------|:----------|---------------:|
| google play - Mình khuyên các bạn nên mua bên Lazada hoặc Tiki chứ không nên mua Shopee nhé . Có vấn đề gì gửi mail thì trả lời như không , không giải quyết được đâu , tốn thời gian .                                                                    | google play | Services  |       0.749757 |
| google play - Con cc quoảng cáu ít thôi                                                                                                                                                                                                                    | google play | Others    |       0.845028 |
| ios - Mình có một vài món hàng shipper ấn giao r mà chưa đưa mình hàng hay đơn hàng hơn tháng vẫn chưa nhận dù có liên hệ với trợ giúp để yêu cầu liên hệ với shipper nm họ chỉ xl và cứ thế cho 1 tuần trôi qua tiếp . app sd đôi khi cũng giật với lag . | ios         | Delivery  |       0.963248 |
| google play - Mình đã sử dụng shoppe cũng 1 thời gian dài rồi nhưng mới đây là trải nghiệm tồi tệ nhất mà mình từng gặp và shoppe không chịu giải quyết vấn đề và đã đổ lỗi lại cho mình . Mình thật sự rất thất vọng về cách hành xử của shoppe ạ         | google play | Services  |       0.702858 |
| google play - Chăm sóc khách hàng quá tệ . Nhân viên hỗ trợ có cũng như không                                                                                                                                                                              | google play | Services  |       0.943015 |

We can even predict top k results

```python
df_result = controller.predict_ddict(ddict=test_ddict,ds_type='test',topk=3)
df_result.head()
```

| text                                                                                                                                                                                                                                                       | Source      | pred_L1   | pred_prob_L1                       | pred_L1_top1   | pred_L1_top2   | pred_L1_top3   |   pred_prob_L1_top1 |   pred_prob_L1_top2 |   pred_prob_L1_top3 |
|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:------------|:----------|:-----------------------------------|:---------------|:---------------|:---------------|--------------------:|--------------------:|--------------------:|
| google play - Mình khuyên các bạn nên mua bên Lazada hoặc Tiki chứ không nên mua Shopee nhé . Có vấn đề gì gửi mail thì trả lời như không , không giải quyết được đâu , tốn thời gian .                                                                    | google play | [8 7 5]   | [0.7497572  0.11502659 0.06754405] | Services       | Return/Refund  | Others         |            0.749757 |           0.115027  |          0.0675441  |
| google play - Con cc quoảng cáu ít thôi                                                                                                                                                                                                                    | google play | [5 1 3]   | [0.8450278  0.11246138 0.02705124] | Others         | Commercial     | Feature        |            0.845028 |           0.112461  |          0.0270512  |
| ios - Mình có một vài món hàng shipper ấn giao r mà chưa đưa mình hàng hay đơn hàng hơn tháng vẫn chưa nhận dù có liên hệ với trợ giúp để yêu cầu liên hệ với shipper nm họ chỉ xl và cứ thế cho 1 tuần trôi qua tiếp . app sd đôi khi cũng giật với lag . | ios         | [2 3 5]   | [0.9632478  0.01823515 0.00765338] | Delivery       | Feature        | Others         |            0.963248 |           0.0182352 |          0.00765338 |
| google play - Mình đã sử dụng shoppe cũng 1 thời gian dài rồi nhưng mới đây là trải nghiệm tồi tệ nhất mà mình từng gặp và shoppe không chịu giải quyết vấn đề và đã đổ lỗi lại cho mình . Mình thật sự rất thất vọng về cách hành xử của shoppe ạ         | google play | [8 5 7]   | [0.7028584  0.10196633 0.10041263] | Services       | Others         | Return/Refund  |            0.702858 |           0.101966  |          0.100413   |
| google play - Chăm sóc khách hàng quá tệ . Nhân viên hỗ trợ có cũng như không                                                                                                                                                                              | google play | [8 5 7]   | [0.9430152  0.03820571 0.00792477] | Services       | Others         | Return/Refund  |            0.943015 |           0.0382057 |          0.00792477 |

If we just want to make a prediction on a small amount of data (single sentence, or a few sentences), we can use `ModelController.predict_raw_text`

In [ ]:
# Since we have some metadatas, we need to define a dictionary (to imitate a DatasetDict)
raw_content={
    'Source': 'Google play',
    'Content':'Tôi không thích Shopee.Tại vì dùng app rất chậm,lag banh nhà lầu, thậm chí log in còn không đc'
}

If we don't use metadata, we can use something like this: 

```raw_content='Tôi không thích Shopee.Tại vì dùng app rất chậm,lag banh nhà lầu, thậm chí log in còn không đc'```

```python
df_result = controller.predict_raw_text(raw_content,topk=1)
df_result
```

| text                                                                                                              | Source      | pred_L1   |   pred_prob_L1 |
|:------------------------------------------------------------------------------------------------------------------|:------------|:----------|---------------:|
| google play - Tôi không thích Shopee . Tại vì dùng app rất chậm , lag banh nhà lầu , thậm chí log in còn không đc | google play | Feature   |       0.993081 |

## Predict using trained model, using tokenized DatasetDict

### Load trained model

```python
num_classes = 10

_model_kwargs={
    'concathead_class': RobertaConcatHeadSimple,
    'classifier_dropout':0.1,
    'last_hidden_size':768,  
    'is_multilabel':False, 
    'is_multihead':False,
    'head_class_sizes':num_classes
}

trained_model = model_init_classification(model_class = RobertaHiddenStateConcatForSequenceClassification,
                                  cpoint_path = Path('./sample_weights/model_progress'), 
                                  output_hidden_states=True,
                                  seed=42,
                                  model_kwargs = _model_kwargs)
```

```python
metric_funcs = [partial(f1_score,average='macro'),accuracy_score]
controller = ModelController(model,metric_funcs)
```

### Predict

In [ ]:
main_ddict

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'Source', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 146
    })
    validation: Dataset({
        features: ['text', 'label', 'Source', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 14
    })
})

In [ ]:
my_label_name = 'L1'
my_class_predefined = ['Buyer complained seller',
 'Commercial',
 'Delivery',
 'Feature',
 'Order/Item',
 'Others',
 'Payment',
 'Return/Refund',
 'Services',
 'Shopee account']

```python
df_val = controller.predict_ddict(main_ddict,
                                  ds_type='validation',
                                  is_multilabel=False,
                                  tokenizer=tokenizer,
                                  label_names = my_label_name,
                                  class_names_predefined=my_class_predefined
                                  )
df_val.head()
```

| text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |   label | Source      | pred_L1                 |   pred_prob_L1 |
|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------:|:------------|:------------------------|---------------:|
| owned - [ Cảnh báo ] bán fa.ke giả mạo Shop Mall . Mọi người ơi , đêm qua mình vừa mua shop này chai dầu dưỡng tóc . Do tối buồn ngủ nên mình mắt nhắm mắt mở đặt shop này . Sáng ra khi check lại đơn thì mình mới phát hình shop này đã photoshop , chèn tag Mall vào hình ảnh sản phẩm mặc dù shop không có tag gì hết . Mình vội vàng hủy đơn và rp đến Shopee . Mọi người mua hàng nhớ cẩn thận check hình ảnh và uy tín shop rõ ràng nha : ( ( ( ( # NghienShopee # Canhbao # Fake                                     |       0 | owned       | Buyer complained seller |       0.78914  |
| google play - Chính sách trả hàng hoàn tiền không hợp lý . Thiếu công bằng , không bảo vệ quyền lợi của người bán . Mình đã tắt bán hàng trên Shopee và chuyển sang lazada .                                                                                                                                                                                                                                                                                                                                                 |       7 | google play | Return/Refund           |       0.976054 |
| google play - Hi vọng shopee kiểm duyệt phản hồi đánh giá của khách hàng chặt chẽ và chính xác hơn . Bởi vì có nhiều người chụp đăng hình ảnh ko liên quan và những ký tự vô nghĩa gggghkkkdjdbdjdbsosb nhằm mục đích nhận xu , không có giá trị tham khảo cho những người mua sau mà shopee vẫn cho đăng . Còn mình đánh giá càng chi tiết , muốn đem lại giá trị tham khảo cho người sau thì bị hệ thống kêu trùng lặp ký tự , phải chỉnh sửa cả chục cả trăm lần rất mất thời gian , vẫn không hợp lệ và ko có cho đăng . |       3 | google play | Feature                 |       0.582839 |
| google play - Shoppe bị lỗi r ....                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |       5 | google play | Feature                 |       0.760949 |
| google play - Hàng không đặt được gì hết một sao                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |       9 | google play | Others                  |       0.735695 |