# Model Controller Tutorial: EnviBert model with Deep Hierarchical Classification

> This notebook contains some example of how to use the EnviBert-based models in this NLP library

- skip_showdoc: true
- skip_exec: true

We will walk through other cases of classification: multi-head and multi-label. Since we will showcase the capabiilty of this label in these cases, there won't be as detailed as [this tutorial](https://anhquan0412.github.io/that-nlp-library/model_main_envibert.html)

In [ ]:
%reload_ext autoreload
%autoreload 2

In [ ]:
#| hide
from nbdev.showdoc import *

## Load data

In [ ]:
from that_nlp_library.text_transformation import *
from that_nlp_library.text_augmentation import *
from that_nlp_library.text_main import *

In [ ]:
from underthesea import text_normalize
from functools import partial
from pathlib import Path
from importlib.machinery import SourceFileLoader
from transformers import DataCollatorWithPadding

Define some necessary text augmentations and text transformations

> For Text Transformation

In [ ]:
txt_tfms=[text_normalize]

> For Text Augmentation

In [ ]:
over_nonown_tfm = partial(sampling_with_condition,query='Source=="non owned"',frac=0.5,seed=42,apply_to_all=False)
over_nonown_tfm.__name__ = 'Oversampling Non Owned'

over_own_tfm = partial(sampling_with_condition,query='Source=="owned"',frac=2,seed=42,apply_to_all=False)
over_own_tfm.__name__ = 'Oversampling Owned'

over_hc_tfm = partial(sampling_with_condition,query='Source=="hc search"',frac=2.5,seed=42,apply_to_all=False)
over_hc_tfm.__name__ = 'Oversampling HC search'

remove_accent_tfm = partial(remove_vnmese_accent,frac=1,seed=42,apply_to_all=True)
remove_accent_tfm.__name__ = 'Add No-Accent Text'

aug_tfms = [over_nonown_tfm,over_own_tfm,over_hc_tfm,remove_accent_tfm]

Create a TextDataMain object

In [ ]:
DATA_PATH = Path('secret_data')

In [ ]:
tdm = TextDataMain.from_csv(DATA_PATH/'buyer_listening_with_all_raw_data_w151617.csv',
                            return_df=False,
                            main_content='Content',
                            metadatas='Source',
                            label_names=['L1','L2'],
                            val_ratio=0.24,
                            split_cols='L1',
                            content_tfms = txt_tfms,
                            aug_tfms = aug_tfms,
                            process_metadatas=True,
                            seed=42,
                            shuffle_trn=True)

----- Input Validation Precheck -----
DataFrame contains missing values!
-----> List of columns and the number of missing values for each
is_valid    65804
dtype: int64
DataFrame contains duplicated values!
-----> Number of duplications: 7 rows

Define our tokenizer for EnviBert

In [ ]:
cache_dir=Path('./envibert_tokenizer')
tokenizer = SourceFileLoader("envibert.tokenizer", 
                             str(cache_dir/'envibert_tokenizer.py')).load_module().RobertaTokenizer(cache_dir)

Create our DatasetDict from TextDataMain (as our `ModelController` class can also work with DatasetDict)

In [ ]:
main_ddict= tdm.to_datasetdict(tokenizer,
                               max_length=512,
                               trn_ratio=0.1)

-------------------- Start Main Text Processing --------------------
----- Metadata Simple Processing & Concatenating to Main Content -----
----- Label Encoding -----
-------------------- Text Transformation --------------------
----- text_normalize -----

100%|█████████████████████████████████| 112453/112453 [00:28<00:00, 3911.78it/s]

-------------------- Train Test Split --------------------
Previous Validation Percentage: 24.0%
- Before leak check
Size: 26989
- After leak check
Size: 23930
- Number of rows leaked: 3059, or 11.33% of the original validation (or test) data
Current Validation Percentage: 21.28%
-------------------- Text Augmentation --------------------
Train data size before augmentation: 88523
----- Oversampling Non Owned -----
Train data size after THIS augmentation: 98345
----- Oversampling Owned -----
Train data size after THIS augmentation: 109231
----- Oversampling HC search -----
Train data size after THIS augmentation: 116233
----- Add No-Accent Text -----

100%|████████████████████████████████| 116233/116233 [00:06<00:00, 19238.67it/s]

Train data size after THIS augmentation: 232466
Train data size after ALL augmentation: 232466
-------------------- Map Tokenize Function --------------------

Map:   0%|          | 0/23246 [00:00<?, ? examples/s]

Map:   0%|          | 0/23930 [00:00<?, ? examples/s]

In [ ]:
main_ddict

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'Source', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 23246
    })
    validation: Dataset({
        features: ['text', 'label', 'Source', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 23930
    })
})

In [ ]:
main_ddict['validation']['label'][:5]

[[0, 55], [7, 25], [3, 47], [5, 12], [9, 7]]

# Model Experiment: EnviBert Multi-Head Classification (with Hidden Layer Concatenation)

In [ ]:
# from that_nlp_library.models.classifiers import *
from that_nlp_library.models.deep_hierarchical_classifiers import *
from that_nlp_library.model_main import *
from that_nlp_library.models.classifiers import *

comet_ml is installed but `COMET_API_KEY` is not set.

In [ ]:
from sklearn.metrics import f1_score, accuracy_score
import os
import torch

This will specify a (or a list) of GPUs for training

In [ ]:
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

## Build DHC Conditional Mask

In [ ]:
df_labels = tdm.df[tdm.label_names]

In [ ]:
df_labels.head()

  L1  L2
0  3   5
1  5  52
2  1  60
3  7  25
4  5  12

In [ ]:
dhc_mask = build_DHC_conditional_mask(df_labels,*tdm.label_names)

In [ ]:
dhc_mask.shape

torch.Size([10, 67])

Explain the first row of the mask (for level 1 label "Buyer Complained Seller")

In [ ]:
dhc_mask[0]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Slicing the first portion for label 2, show string for True mask

In [ ]:
for i in torch.where(dhc_mask[0]==1)[0]:
    print(tdm.label_lists[1][i])

Customer service (didn't respond/impolite)
Illegal/counterfeit products
Product description
Product quality
Sellers cancelled order without any advanced notice/reason
Sellers cheated Buyers (Sellers tried to reach me outside of Shopee App)
Sellers packed fake orders

## Train EnviBert (with hidden layer concatenation), using TDM

Let's create our model controller

In [ ]:
model_name='nguyenvulebinh/envibert'

_model_kwargs={
    'dhc_mask':dhc_mask,
    'classifier_dropout':0.1,
    'last_hidden_size':768,  
    'linear_l1_size':389,
    'linear_l2_size':417,
    'lloss_weight':1.0,
    'dloss_weight':0.8,
    
}

model = model_init_classification(model_class = RobertaHSCDHCSequenceClassification,
                                  cpoint_path = 'nguyenvulebinh/envibert', 
                                  output_hidden_states=True, # since we are using 'hidden layer contatenation'
                                  seed=42,
                                  model_kwargs = _model_kwargs)
metric_funcs = [partial(f1_score,average='macro'),accuracy_score]
controller = ModelController(model,tdm,metric_funcs)

Some weights of the model checkpoint at nguyenvulebinh/envibert were not used when initializing RobertaHSCDHCSequenceClassification: ['lm_head.dense.bias', 'lm_head.bias', 'lm_head.layer_norm.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.weight']
- This IS expected if you are initializing RobertaHSCDHCSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaHSCDHCSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaHSCDHCSequenceClassification were not initialized from the model checkpoint at nguyenvulebinh/envibert and are newly initialized: ['linear_L2.weight', 'linear_L1.weight', 'linear_L1_logit.bias', 'linear_L1_logit.weight', 'linear_L2_logit.bias', 'linear_L2.bias', 'linear_L1.bias', 'root_representation.pre_classifier.bias', 'root_representation.pre_classifier.weight', 'linear_L2_logit.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

And we can start training our model

In [ ]:
lr = 7e-5
bs=8
wd=0.01
epochs= 2

In [ ]:
controller.fit(epochs,lr,
               batch_size=bs,
               weight_decay=wd,
               save_checkpoint=False,
#                o_dir='sample_weights',
               compute_metrics=compute_metrics_separate_singleheads,
               head_sizes=[len(tdm.label_lists[0]),len(tdm.label_lists[1])]
              )

/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2372: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2372: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [ ]:
controller.trainer.model.save_pretrained('./sample_weights/my_model')

## Predict using trained model, using TDM

### Load trained model

In [ ]:
model = model_init_classification(model_class = RobertaHSCDHCSequenceClassification,
                                  cpoint_path = './sample_weights/my_model', 
                                  output_hidden_states=True, # since we are using 'hidden layer contatenation'
                                  seed=42,
                                  model_kwargs = _model_kwargs)
metric_funcs = [partial(f1_score,average='macro'),accuracy_score]
controller = ModelController(model,tdm,metric_funcs)

### Predict Train/Validation set

Make prediction on all validation set

In [ ]:
df_val = controller.predict_ddict(ds_type='validation',is_dhc=True)

-------------------- Start making predictions --------------------

Map:   0%|          | 0/23930 [00:00<?, ? examples/s]

In [ ]:
df_val.head()

,text,label,Source,pred_L1,pred_prob_L1,pred_L2,pred_prob_L2
0,owned - [ Cảnh báo ] bán fa.ke giả mạo Shop Ma...,"[0, 55]",owned,Others,0.489046,Seller,0.453078
1,google play - Chính sách trả hàng hoàn tiền kh...,"[7, 25]",google play,Return/Refund,0.789575,Dispute,0.504691
2,google play - Hi vọng shopee kiểm duyệt phản h...,"[3, 47]",google play,Feature,0.410733,Review & Rating,0.279649
3,google play - Shoppe bị lỗi r ....,"[5, 12]",google play,Feature,0.816540,App performance,0.743287
4,google play - Hàng không đặt được gì hết một sao,"[9, 7]",google play,Others,0.694718,Cannot defined,0.632161

In [ ]:
df_val.head()

,text,label,Source,pred_L1,pred_prob_L1,pred_L2,pred_prob_L2
0,owned - [ Cảnh báo ] bán fa.ke giả mạo Shop Ma...,"[0, 55]",owned,Others,0.376488,Seller,0.318077
1,google play - Chính sách trả hàng hoàn tiền kh...,"[7, 25]",google play,Others,0.214118,Dispute,0.700250
2,google play - Hi vọng shopee kiểm duyệt phản h...,"[3, 47]",google play,Others,0.173230,Contact Agent,0.279465
3,google play - Shoppe bị lỗi r ....,"[5, 12]",google play,Feature,0.454503,Cannot defined,0.471248
4,google play - Hàng không đặt được gì hết một sao,"[9, 7]",google play,Others,0.396479,Cannot defined,0.703143

### Predict Test set

We will go through details on how to make a prediction on a completely new and raw dataset using our trained model. For now, let's reuse the sample csv and pretend it's our test set

In [ ]:
df_test = TextDataMain.from_csv(Path('sample_data')/'sample.csv',return_df=True)

----- Input Validation Precheck -----

We will remove all the labels and unnecessary columns

In [ ]:
df_test = df_test.drop(['L1','L2'],axis=1)

In [ ]:
df_test.head()

         Group       Source                                            Content
0  Google Play  Google Play  Mình khuyên các bạn nên mua bên Lazada hoặc Ti...
1  Google Play  Google Play                          Con cc quoảng cáu ít thôi
2          iOS          iOS  Mình có một vài món hàng shipper ấn giao r mà ...
3  Google Play  Google Play  Mình đã sử dụng shoppe cũng 1 thời gian dài rồ...
4  Google Play  Google Play  Chăm sóc khách hàng quá tệ. Nhân viên hỗ trợ c...

We will create a DatasetDict for this test dataframe

In [ ]:
test_ddict = tdm.get_test_datasetdict_from_df(df_test)

-------------------- Getting Test Set --------------------
----- Input Validation Precheck -----
-------------------- Start Test Set Transformation --------------------
----- Metadata Simple Processing & Concatenating to Main Content -----
-------------------- Text Transformation --------------------
----- text_normalize -----

100%|█████████████████████████████████████████| 70/70 [00:00<00:00, 6050.27it/s]

-------------------- Test Leak Checking --------------------
- Before leak check
Size: 70

- After leak check
Size: 0
- Number of rows leaked: 70, or 100.00% of the original validation (or test) data
-------------------- Construct DatasetDict --------------------

Map:   0%|          | 0/70 [00:00<?, ? examples/s]

Remember the ***Leak Check*** we did in TextDataMain? Our ```df_test``` only has 70 rows, and it also shows that 70 rows of our data is leaked (100%), which is correct because this test dataset is actually a small sample of the training data.

In [ ]:
test_ddict

DatasetDict({
    test: Dataset({
        features: ['text', 'Source', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 70
    })
})

Our test data has been processed + transformed (but not augmented) the same way as the validation set. Now we can start making the prediction

In [ ]:
controller = ModelController(model,tdm)
df_result = controller.predict_ddict(ddict=test_ddict,ds_type='test',is_dhc=True)

-------------------- Start making predictions --------------------

Map:   0%|          | 0/70 [00:00<?, ? examples/s]

/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2372: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [ ]:
df_result.head()

,text,Source,pred_L1,pred_prob_L1,pred_L2,pred_prob_L2
0,google play - Mình khuyên các bạn nên mua bên ...,google play,Services,0.263348,Contact Agent,0.308041
1,google play - Con cc quoảng cáu ít thôi,google play,Others,0.664586,Cannot defined,0.763777
2,ios - Mình có một vài món hàng shipper ấn giao...,ios,Delivery,0.903787,Driver,0.569975
3,google play - Mình đã sử dụng shoppe cũng 1 th...,google play,Services,0.326076,Contact Agent,0.374300
4,google play - Chăm sóc khách hàng quá tệ . Nhâ...,google play,Services,0.239295,Contact Agent,0.279015

We can even predict top k results

In [ ]:
df_result = controller.predict_ddict(ddict=test_ddict,ds_type='test',is_dhc=True,topk=3)
df_result.head()

-------------------- Start making predictions --------------------

Map:   0%|          | 0/70 [00:00<?, ? examples/s]

/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2372: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

,text,Source,pred_L1,pred_prob_L1,pred_L2,pred_prob_L2,pred_L1_top1,pred_L1_top2,pred_L1_top3,pred_prob_L1_top1,pred_prob_L1_top2,pred_prob_L1_top3,pred_L2_top1,pred_L2_top2,pred_L2_top3,pred_prob_L2_top1,pred_prob_L2_top2,pred_prob_L2_top3
0,google play - Mình khuyên các bạn nên mua bên ...,google play,"[8, 0, 7]","[0.26334786, 0.19301814, 0.15388776]","[17, 25, 12]","[0.30804068, 0.121777885, 0.073863074]",Services,Buyer complained seller,Return/Refund,0.263348,0.193018,0.153888,Contact Agent,Dispute,Cannot defined,0.308041,0.121778,0.073863
1,google play - Con cc quoảng cáu ít thôi,google play,"[5, 1, 3]","[0.6645862, 0.275267, 0.040605642]","[12, 44, 5]","[0.7637775, 0.15609594, 0.028883968]",Others,Commercial,Feature,0.664586,0.275267,0.040606,Cannot defined,Promotions,App performance,0.763777,0.156096,0.028884
2,ios - Mình có một vài món hàng shipper ấn giao...,ios,"[2, 4, 5]","[0.90378714, 0.033022527, 0.023563333]","[26, 23, 22]","[0.5699748, 0.1762967, 0.07040981]",Delivery,Order/Item,Others,0.903787,0.033023,0.023563,Driver,Delivery time,Delivery status/info,0.569975,0.176297,0.070410
3,google play - Mình đã sử dụng shoppe cũng 1 th...,google play,"[8, 0, 5]","[0.326076, 0.17045896, 0.12246474]","[17, 12, 43]","[0.37429976, 0.06884557, 0.064494275]",Services,Buyer complained seller,Others,0.326076,0.170459,0.122465,Contact Agent,Cannot defined,Product quality,0.374300,0.068846,0.064494
4,google play - Chăm sóc khách hàng quá tệ . Nhâ...,google play,"[8, 0, 5]","[0.23929471, 0.21401595, 0.19128971]","[17, 12, 25]","[0.27901503, 0.11786536, 0.09214289]",Services,Buyer complained seller,Others,0.239295,0.214016,0.191290,Contact Agent,Cannot defined,Dispute,0.279015,0.117865,0.092143

If we just want to make a prediction on a small amount of data (single sentence, or a few sentences), we can use `ModelController.predict_raw_text`

In [ ]:
# Since we have some metadatas, we need to define a dictionary (to imitate a DatasetDict)
raw_content={
    'Source': 'Google play',
    'Content':'Tôi không thích Shopee.Tại vì dùng app rất chậm,lag banh nhà lầu, thậm chí log in còn không đc'
}

If we don't use metadata, we can use something like this: 

```raw_content='Tôi không thích Shopee.Tại vì dùng app rất chậm,lag banh nhà lầu, thậm chí log in còn không đc'```

In [ ]:
df_result = controller.predict_raw_text(raw_content,is_dhc=True)
df_result

100%|███████████████████████████████████████████| 1/1 [00:00<00:00, 4718.00it/s]

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2372: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

,text,Source,pred_L1,pred_prob_L1,pred_L2,pred_prob_L2
0,google play - Tôi không thích Shopee . Tại vì ...,google play,Feature,0.974891,App performance,0.964083

In [ ]:
raw_content={
    'Source': ['Google play','Owned'],
    'Content':['Tôi không thích Shopee.Tại vì dùng app rất chậm,lag banh nhà lầu, thậm chí log in còn không đc','App này xài được']
            }
df_result = controller.predict_raw_text(raw_content,is_dhc=True,topk=2)
df_result

100%|███████████████████████████████████████████| 2/2 [00:00<00:00, 8248.39it/s]

Map:   0%|          | 0/2 [00:00<?, ? examples/s]

Map:   0%|          | 0/2 [00:00<?, ? examples/s]

/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2372: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

,text,Source,pred_L1,pred_prob_L1,pred_L2,pred_prob_L2,pred_L1_top1,pred_L1_top2,pred_prob_L1_top1,pred_prob_L1_top2,pred_L2_top1,pred_L2_top2,pred_prob_L2_top1,pred_prob_L2_top2
0,google play - Tôi không thích Shopee . Tại vì ...,google play,"[3, 5]","[0.97489095, 0.009242541]","[5, 65]","[0.96408296, 0.0073485267]",Feature,Others,0.974891,0.009243,App performance,Sign up/Log in,0.964083,0.007349
1,owned - App này xài được,owned,"[5, 1]","[0.79120094, 0.14251429]","[12, 29]","[0.8515302, 0.043311276]",Others,Commercial,0.791201,0.142514,Cannot defined,Games/Minigames,0.851530,0.043311

# Try different model architecture

In [ ]:
# from that_nlp_library.models.classifiers import *
from that_nlp_library.models.deep_hierarchical_classifiers import *
from that_nlp_library.model_main import *
from that_nlp_library.models.classifiers import *

In [ ]:
from sklearn.metrics import f1_score, accuracy_score
import os
import torch

In [ ]:
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

In [ ]:
df_labels = tdm.df[tdm.label_names]

dhc_mask = build_DHC_conditional_mask(df_labels,*tdm.label_names)

In [ ]:
model_name='nguyenvulebinh/envibert'

_model_kwargs={
    'dhc_mask':dhc_mask,
    'classifier_dropout':0.1,
    'last_hidden_size':768,  
    'linear_l1_size':389,
    'linear_l2_size':417,
    'lloss_weight':1.0,
    'dloss_weight':0.8,
    
}

model = model_init_classification(model_class = RobertaHSCDHCSequenceClassification,
                                  cpoint_path = 'nguyenvulebinh/envibert', 
                                  output_hidden_states=True, # since we are using 'hidden layer contatenation'
                                  seed=42,
                                  model_kwargs = _model_kwargs)
metric_funcs = [partial(f1_score,average='macro'),accuracy_score]
controller = ModelController(model,tdm,metric_funcs)

lr = 7e-5
bs=8
wd=0.01
epochs= 2

controller.fit(epochs,lr,
               batch_size=bs,
               weight_decay=wd,
               save_checkpoint=False,
               compute_metrics=compute_metrics_separate_singleheads,
               head_sizes=[len(tdm.label_lists[0]),len(tdm.label_lists[1])]
              )

Some weights of the model checkpoint at nguyenvulebinh/envibert were not used when initializing RobertaHSCDHCSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight']
- This IS expected if you are initializing RobertaHSCDHCSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaHSCDHCSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaHSCDHCSequenceClassification were not initialized from the model checkpoint at nguyenvulebinh/envibert and are newly initialized: ['linear_L2_logit.bias', 'linear_L1.weight', 'linear_L2_logit.weight', 'linear_L1_logit.bias', 'root_representation.pre_classifier.weight', 'linear_L2.weight', 'linear_L1.bias', 'linear_L1_logit.weight', 'root_representation.pre_classifier.bias', 'linear_L2.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2372: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2372: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [ ]:
model_name='nguyenvulebinh/envibert'

_model_kwargs={
    'dhc_mask':dhc_mask,
    'classifier_dropout':0.1,
    'last_hidden_size':768,  
    'linear_l1_size':389,
    'linear_l2_size':417,
    'lloss_weight':1.0,
    'dloss_weight':0,
    
}

model = model_init_classification(model_class = RobertaHSCDHCSequenceClassification,
                                  cpoint_path = 'nguyenvulebinh/envibert', 
                                  output_hidden_states=True, # since we are using 'hidden layer contatenation'
                                  seed=42,
                                  model_kwargs = _model_kwargs)
metric_funcs = [partial(f1_score,average='macro'),accuracy_score]
controller = ModelController(model,tdm,metric_funcs)

lr = 7e-5
bs=8
wd=0.01
epochs= 2

controller.fit(epochs,lr,
               batch_size=bs,
               weight_decay=wd,
               save_checkpoint=False,
               compute_metrics=compute_metrics_separate_singleheads,
               head_sizes=[len(tdm.label_lists[0]),len(tdm.label_lists[1])]
              )

/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2372: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2372: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [ ]:
model_name='nguyenvulebinh/envibert'

_model_kwargs={
    'dhc_mask':dhc_mask,
    'lloss_weight':1.0,
    'dloss_weight':0.8,
    
}

model = model_init_classification(model_class = RobertaHSCSimpleDHCSequenceClassification,
                                  cpoint_path = 'nguyenvulebinh/envibert', 
                                  output_hidden_states=True, # since we are using 'hidden layer contatenation'
                                  seed=42,
                                  model_kwargs = _model_kwargs)
metric_funcs = [partial(f1_score,average='macro'),accuracy_score]
controller = ModelController(model,tdm,metric_funcs)

lr = 7e-5
bs=8
wd=0.01
epochs= 2

controller.fit(epochs,lr,
               batch_size=bs,
               weight_decay=wd,
               save_checkpoint=False,
               compute_metrics=compute_metrics_separate_singleheads,
               head_sizes=[len(tdm.label_lists[0]),len(tdm.label_lists[1])]
              )

Some weights of the model checkpoint at nguyenvulebinh/envibert were not used when initializing RobertaHSCSimpleDHCSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight']
- This IS expected if you are initializing RobertaHSCSimpleDHCSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaHSCSimpleDHCSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaHSCSimpleDHCSequenceClassification were not initialized from the model checkpoint at nguyenvulebinh/envibert and are newly initialized: ['linear_L2_logit.bias', 'linear_L2_logit.weight', 'linear_L1_logit.bias', 'linear_L2.weight', 'linear_L1_logit.weight', 'linear_L2.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2372: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2372: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [ ]:
model_name='nguyenvulebinh/envibert'

_model_kwargs={
    'dhc_mask':dhc_mask,
    'lloss_weight':1.0,
    'dloss_weight':0,
    
}

model = model_init_classification(model_class = RobertaHSCSimpleDHCSequenceClassification,
                                  cpoint_path = 'nguyenvulebinh/envibert', 
                                  output_hidden_states=True, # since we are using 'hidden layer contatenation'
                                  seed=42,
                                  model_kwargs = _model_kwargs)
metric_funcs = [partial(f1_score,average='macro'),accuracy_score]
controller = ModelController(model,tdm,metric_funcs)

lr = 7e-5
bs=8
wd=0.01
epochs= 2

controller.fit(epochs,lr,
               batch_size=bs,
               weight_decay=wd,
               save_checkpoint=False,
               compute_metrics=compute_metrics_separate_singleheads,
               head_sizes=[len(tdm.label_lists[0]),len(tdm.label_lists[1])]
              )

Some weights of the model checkpoint at nguyenvulebinh/envibert were not used when initializing RobertaHSCSimpleDHCSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight']
- This IS expected if you are initializing RobertaHSCSimpleDHCSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaHSCSimpleDHCSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaHSCSimpleDHCSequenceClassification were not initialized from the model checkpoint at nguyenvulebinh/envibert and are newly initialized: ['linear_L2_logit.bias', 'linear_L2_logit.weight', 'linear_L1_logit.bias', 'linear_L2.weight', 'linear_L1_logit.weight', 'linear_L2.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2372: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

/home/quan/anaconda3/envs/fastai_v2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2372: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(